[workspace]
members = ["crates/feff85exafs-core", "crates/feff85exafs-errors"]
resolver = "3"

[package]
name = "feff85exafs-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
feff85exafs-core = { path = "crates/feff85exafs-core" }
feff85exafs-errors = { path = "crates/feff85exafs-errors" }
